name: Checkout and add folder from other Branch

on:
  workflow_dispatch:

concurrency:
  group: "test-01"
  cancel-in-progress: false
  
permissions:
  contents: write

jobs:
  checkout-add-folder:
    runs-on: ubuntu-20.04
    environment: Test-01
    name: Fetch main
    steps:
    - uses: actions/checkout@v4
    - name: checkout results
      run: |
        git checkout results -- results
    - name: Show folders
      run: |
        sudo apt-get install tree &&
        tree .